Update requirements.txt
sberl/supersid pull request #70
Opened 2023-10-12 18:20 UTC by kunkleb

Error messages occur when installing supersid with the latest version of the RPi OS. I believe the versions of numpy, pandas, and pyalsaaudio have to be updated in requirements.txt These are the versions that I found when searching. numpy 1.23.0, pandas 2.1.1, pyalsaaudio 0.10.0
These work with the fresh install that I did.
New versions did not update until I changed >= to == in requirements.txt The new RPi OS shows python as version 3.9.2

2023-10-12 19:57 UTC, sberl requested changes
Using the == operator here means that if there are bug fix releases to these packages, they will not be picked up. You are locking in the current release.
Instead you can use the ~= operator, which will allow a "compatible release", which is roughly the same as a wildcard for the last part of the release number.
So numpy==1.23.0 should instead by either numpy~=1.23.0, or numpy>=1.23.*

2023-10-12 22:20 UTC, kunkleb commented
I think I understand the operators now.
The original problem was that after the install, numpy was version 1.26.0 which did not work.  After googling around I saw that 1.16.5 to 1.23.0 should work for python 3.9.2.  I then did the same thing for pandas and pyalsaaudio.  
Running the original requirements.txt installed 1.26.0 so I took out the > and replaced it with =. 
I don't know how this should be handled with future releases of RPi.  Maybe just wait until a problem is reported and then revise requirements.txt accordingly?

2023-10-13 13:11 UTC, kunkleb commented
FYI - the tilde works on the RPi.  I tried numpy~=1.23.0  and numpy==1.23.*

2023-10-14 14:00 UTC, kunkleb commented
The changes have been made to the file.  Now using ~=

2024-01-29 21:48 UTC, merged